# permissions for end users to edit schedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scheduler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sfc-at-edge
    app.kubernetes.io/part-of: sfc-at-edge
    app.kubernetes.io/managed-by: kustomize
  name: scheduler-editor-role
rules:
- apiGroups:
  - sfc.automation.dcn.ssu.ac.kr
  resources:
  - schedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sfc.automation.dcn.ssu.ac.kr
  resources:
  - schedulers/status
  verbs:
  - get
