apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
kind: ServiceLevelAgreement
metadata:
  name: sla-streaming-video
  namespace: default
  labels: 
    app: video-streaming
spec:
  connectivity:
    minimumLatency: 30
    maximumPacketLoss: 1
  latencyPercentileScore:
    ninetiethPercentileScore: 30
