apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
kind: ServiceLevelAgreement
metadata:
  labels:
    app.kubernetes.io/name: servicelevelagreement
    app.kubernetes.io/instance: servicelevelagreement-sample
    app.kubernetes.io/part-of: sfc-at-edge
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sfc-at-edge
  name: servicelevelagreement-sample
spec:
  # TODO(user): Add fields here
