apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
kind: ServiceFunctionChain
metadata:
  labels:
    app.kubernetes.io/name: servicefunctionchain
    app.kubernetes.io/instance: servicefunctionchain-sample
    app.kubernetes.io/part-of: sfc-at-edge
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sfc-at-edge
  name: servicefunctionchain-sample
spec:
  # TODO(user): Add fields here
