apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
kind: SFCService
metadata:
  name: process-video-service
  namespace: default
  labels:
    app: process-video-app
    service: process-video-app-service
    chain: video-streaming-chain
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: process-video-app
