apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
kind: ServiceFunctionChain
metadata:
  name: streaming-video-service-chain
  namespace: default
  labels:
    app: video-streaming-chain
spec:
  numberofnode: 3
  defaultSLA: sla-streaming-video
  links:
    - 
      metadata:
        name: chain-link-1
      service:
        connectivity:
          minimumLatency: 30ms
          minimumBandwidthIn: 1Gbs
          minimumBandwidthOut: 1Gbs
          maximumPackageLoss: 1%
        serviceRef:
          kind: SFCService
          namespace: default
          name: upload-video-service
          apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
        targetServiceRef:
          kind: SFCService
          namespace: default
          name: process-video-service
          apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
      deployment:
        kind: SFCDeployment
        namespace: default
        name: upload-video-app
        apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
    - 
        metadata:
          name: chain-link-2
        service:
          connectivity:
            minimumLatency: 30ms
            minimumBandwidthIn: 1Gbs
            minimumBandwidthOut: 1Gbs
          serviceRef:
            kind: SFCService
            namespace: default
            name: process-video-service
            apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
          targetServiceRef:
            kind: SFCService
            namespace: default
            name: publish-video-service
            apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
        deployment:
          kind: SFCDeployment
          namespace: default
          name: process-video-app
          apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
    - 
        metadata:
          name: dead-end
        service:
          connectivity:
            minimumLatency: 30ms
            minimumBandwidthIn: 10Gbs
            minimumBandwidthOut: 10Gbs
            maximumPackageLoss: 5%
          serviceRef:
            kind: SFCService
            namespace: default
            name: publish-video-service
            apiVersion: sfc.automation.dcn.ssu.ac.kr/v1
        deployment:
          kind: SFCDeployment
          namespace: default
          name: publish-video-app
          apiVersion: sfc.automation.dcn.ssu.ac.kr/v1